### PR TITLE
fix reset password form bug

### LINKED ISSUE #101: bug: reset-password page not responding after keying in new password and clicking submit

### PR DESCRIPTION
**Pull request by ngjunkang**
PR summary:
* Fix reset password form bug
* Use tan stack useMutation in verify email

Tests:
* Verify that verify email still works
* Verify that password can be reset

Closes #101.

### CODE REVIEW

**Review by blaketingyu — APPROVED** [review]
LGTM, reset working!

File: frontend/src/components/base/button/black.tsx [hunk 1]
```diff
@@ -0,0 +1,17 @@
...
+      loadHoverColor="neutral-50"
+      className={`mr-2 mb-2 inline-flex items-center bg-[#24292F] px-5 py-2.5 text-center text-sm font-medium text-white focus:outline-none focus:ring-4 focus:ring-[#24292F]/50 hover:bg-[#24292F]/90 dark:focus:ring-gray-500 dark:hover:bg-[#050708]/30 ${className}`}
+      {...other}
+    >
+      {children}
+    </BaseButton>
+  );
+}
+//text-white bg-[#24292F] hover:bg-[#24292F]/90 focus:ring-4 focus:outline-none focus:ring-[#24292F]/50 font-medium rounded-lg text-sm px-5 py-2.5 text-center inline-flex items-center dark:focus:ring-gray-500 dark:hover:bg-[#050708]/30 mr-2 mb-2
+//hover:border-black-700 hover:bg-black-700 border-black bg-black text-neutral-50 ${className}
```
Comment (ngjunkang) [inline frontend/src/components/base/button/black.tsx:17]: this is the comments I'm talking about, @blaketingyu

Comment (blaketingyu) [reply frontend/src/components/base/button/black.tsx:17]: Ohh thanks dad @ngjunkang

**Review by aidanaden — APPROVED** [review]
