### PR TITLE
Fix cookie options for local and prod

### LINKED ISSUE #106: bug: login does not work in safari

### PR DESCRIPTION
**Pull request by ngjunkang**
Now backend prod needs to have a new env variable as follows, `NEST_ENV=prod`, optional for local environment

closes #106.

### CODE REVIEW

File: backend/src/config/options.ts [hunk 1]
```diff
@@ -1,17 +1,19 @@
 import { CorsOptions } from "@nestjs/common/interfaces/external/cors-options.interface";
 import { CookieOptions } from "express";
 
+const PRODUCTION = process.env.NEST_ENV === "prod";
```
Comment (aidanaden) [inline backend/src/config/options.ts:4]: think might be better to use the `FRONTEND_URL` env variable to determine if it's production or not (if `FRONTEND_URL.includes("localhost") ? "dev" : "prod"`)

**Review by aidanaden — CHANGES_REQUESTED** [review]

**Review by aidanaden — APPROVED** [review]

**Review by blaketingyu — APPROVED** [review]
